norm_cfg: &norm_cfg {type: BN, requires_grad: True}
model:
  type: MMSegModel
  backbone:
    type: mmseg.PVT_b2
    pretrained: ./weights/pvt_v2_b2.pth
  decode_head:
    type: DAFormerHead
    channels: 256
    dropout_ratio: 0.1
    num_classes: 1
    norm_cfg: *norm_cfg
    align_corners: False
    decoder_params:
      embed_dims: 256
      embed_cfg: {type: mlp, act_cfg: null, norm_cfg: null}
      embed_neck_cfg: {type: mlp, act_cfg: null, norm_cfg: null}
      fusion_cfg: 
        type: conv
        kernel_size: 3
        act_cfg: {type: ReLU}
        norm_cfg: *norm_cfg