model:
  type: MMSegModel
  backbone:
    type: mmseg.PVT_b2
    pretrained: ./weights/pvt_v2_b2.pth
  neck:
    type: FPN
    in_channels: [64, 128, 320, 512]
    out_channels: 256
    num_outs: 4
  decode_head:
    type: FPNHead
    in_channels: [256, 256, 256, 256]
    in_index: [0, 1, 2, 3]
    feature_strides: [4, 8, 16, 32]
    channels: 128
    dropout_ratio: 0.1
    norm_cfg: {type: 'BN', requires_grad: True}
    align_corners: False
    num_classes: 1
