name: smpmodel_f1
version: f3
fold: &fold 3
# folds is 5, which is used to split train and valid datasets


model:
  type: SMPModel
  model_type: UnetPlusPlus
  model_name: timm-efficientnet-b0
  in_channels: 6
  pretrained_weight: noisy-student
  num_classes: 1
loss: [{
  type: BCEWithIgnoreLoss,
  loss_name: bce_loss,
  ignore_index: 255,
  loss_weight: 1.0,
}, {
  type: DiceLoss,
  loss_name: dice_loss,
  loss_weight: 16.0,
}]

metric:
  type: DiceMetric

data:
  type: ConcatData
  fold: 0
  num_folds: 5
  batch_size: 16
  stratified_by: null
  group_by: null
  dataset:
    resize: &resize 512
    trans: {
      train: {type: Compose, transforms: [
        {type: Resize, height: *resize, width: *resize},
        {type: HorizontalFlip, p: 0.5},
        {type: VerticalFlip, p: 0.5},
        {type: Normalize},
        {type: ToTensorV2},
      ], additional_targets: {imageB: image}},
      val: {type: Compose, transforms: [
        {type: Resize, height: *resize, width: *resize},
        {type: Normalize},
        {type: ToTensorV2},
      ], additional_targets: {imageB: image}}
    }

train:
  # optimizer
  optimizer: adamw
  learning_rate: 1e-3
  weight_decay: 1e-3

  # scheduler
  num_epochs: 100
  scheduler: one_cycle

  # trainer
  monitor: val_dice
  log_step: 50
  val_interval: 1
  swa: False
  grad_clip: 2.0
  strategy: dp