model:
  type: MMSegModel
  backbone:
    type: timm
    model_name: resnet18
    in_chans: 3
  decode_head:
    type: UPerHead
    pool_scales: [1, 2, 3, 6]
    channels: 512
    dropout_ratio: 0.1
    num_classes: 1
    norm_cfg: {type: BN, requires_grad: True}
    align_corners: False